ALTER TABLE client_metrics 
  ADD COLUMN IF NOT EXISTS active_clients INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS churned_end_of_contract INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS churned_cancellation INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS upsells_expansions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clients_at_risk INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_client_tenure_months DECIMAL(4,1),
  ADD COLUMN IF NOT EXISTS clients_over_6_months INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clients_3_to_6_months INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clients_under_3_months INTEGER DEFAULT 0;